<?php
print ' <h6> Bat care form coming soon </h6>

<!-- Image Map Generated by http://www.image-map.net/ -->
<!-- image map -->
<img src="https://rescuecentre.org.uk/wp-content/uploads/2024/08/bat-care.png" usemap="#image-map">

<map name="image-map">
    <area target="" alt="1st finger" title="Left 1st finger" href="" coords="38,64,71,34,93,28,135,18,149,16,107,27,61,44" shape="poly">
    <area target="" alt="2nd finger" title="Left 2nd finger" href="" coords="38,69,60,56,79,43,104,31,136,24,118,30,87,40,53,62" shape="poly">
    <area target="" alt="3rd finger" title="Left 3rd finger" href="" coords="65,111,75,87,92,71,111,55,135,36,153,20,122,44,99,63,81,82,73,99" shape="poly">
    <area target="" alt="4th finger" title="Left 4th finger" href="" coords="154,132,143,99,145,74,147,46,154,22,149,52,144,85" shape="poly">
    <area target="" alt="Left forearm" title="Left forearm" href="" coords="158,21,235,62,227,66" shape="poly">
    <area target="" alt="Left humerus" title="Left humerus" href="" coords="226,63,266,42,265,48,230,66" shape="poly">
    <area target="" alt="Left femur" title="Left femur" href="" coords="276,115,248,131,252,136,276,122" shape="poly">
    <area target="" alt="Left tibia" title="Left tibia" href="" coords="246,132,242,159,246,163,251,137" shape="poly">
    <area target="" alt="Left plagiopatagium" title="Left plagiopatagium" href="" coords="154,22,228,67,265,49,262,73,265,95,274,114,248,131,241,149,218,125,193,116,173,122,161,131,157,143,145,94" shape="poly">
    <area target="" alt="Left dactylopatagium major title="Left dactylopatagium major" href="" coords="67,111,79,88,152,21,142,96,154,139,115,114" shape="poly">
    <area target="" alt="dor_L_dactylopatagium_medius" title="Left dactylopatagium medius" href="" coords="10,106,15,88,40,67,94,38,134,23,148,22,104,57,92,71,76,83,64,111,40,99" shape="poly">
    <area target="" alt="dor_L_dactylopatagium_minus" title="Left dactylopatagium minus" href="" coords="45,60,75,37,123,23" shape="poly">
    <area target="" alt="dor_L_uropatagium" title="Left uropatagium" href="" coords="248,157,252,136,278,123,292,127,293,149,293,171,275,154" shape="poly">
    <area target="" alt="dor_L_FA_membrane" title="Left forarm membrane" href="" coords="171,27,232,63,254,52,270,41,234,47,206,43" shape="poly">
    <area target="" alt="dor_R_1st_finger" title="Right first finger" href="" coords="434,17,509,34,542,60,570,87,553,70,524,44,484,28" shape="poly">
    <area target="" alt="dor_R_2nd_finger" title="dor_R_2nd_finger" href="" coords="430,17,513,45,550,67,570,91,554,76,526,54,470,31" shape="poly">
    <area target="" alt="dor_R-3rd_finger" title="dor_R-3rd_finger" href="" coords="436,22,491,66,510,86,521,112,513,98,495,72,466,47" shape="poly">
    <area target="" alt="dor_R-4th_finger" title="dor_R-4th_finger" href="" coords="432,27,443,94,435,144,438,137,446,100,441,55,436,20" shape="poly">
    <area target="" alt="dor_R_humerus" title="dor_R_humerus" href="" coords="322,39,358,59,358,64,323,50" shape="poly">
    <area target="" alt="dor_R_forearm" title="dor_R_forearm" href="" coords="357,59,427,19,428,25,358,66" shape="poly">
    <area target="" alt="dor_R_femur" title="dor_R_femur" href="" coords="317,116,343,132,341,137,316,122" shape="poly">
    <area target="" alt="dor_R_tibia" title="dor_R_tibia" href="" coords="339,136,343,157,346,152,344,137" shape="poly">
    <area target="" alt="dor_R_plagiopatagium" title="dor_R_plagiopatagium" href="" coords="324,50,360,67,430,23,444,96,435,140,392,120,356,136,347,155,341,129,316,115,328,96,330,68" shape="poly">
    <area target="" alt="dor_R-dactylopatagium_major" title="dor_R-dactylopatagium_major" href="" coords="440,26,506,83,520,110,488,110,448,125,436,135" shape="poly">
    <area target="" alt="dor_R_dactylopatagium_medius" title="dor_R_dactylopatagium_medius" href="" coords="440,22,512,47,566,87,579,106,555,100,530,105,518,113,502,77" shape="poly">
    <area target="" alt="dor_R_dactylopatagium_minus" title="dor_R_dactylopatagium_minus" href="" coords="447,19,506,34,541,61,504,42" shape="poly">
    <area target="" alt="dor_R_FA_membrane" title="dor_R_FA_membrane" href="" coords="326,42,363,48,384,40,362,57,352,56" shape="poly">
    <area target="" alt="dor_R_uropatagium" title="dor_R_uropatagium" href="" coords="294,130,295,173,310,159,331,156,342,156,338,136,313,122" shape="poly">
    <area target="" alt="dor_L_thumb" title="dor_L_thumb" href="" coords="155,15,9" shape="circle">
    <area target="" alt="dor_R_thumb" title="dor_R_thumb" href="" coords="434,13,8" shape="circle">
    <area target="" alt="dor_L_foot" title="dor_L_foot" href="" coords="234,170,13" shape="circle">
    <area target="" alt="dor_R_foot" title="dor_R_foot" href="" coords="355,173,11" shape="circle">
    <area target="" alt="dor_L_ear" title="dor_L_ear" href="" coords="274,31,294,31,294,24,270,15" shape="poly">
    <area target="" alt="dor_R_ear" title="dor_R_ear" href="" coords="299,20,317,14,316,21,311,30,299,29" shape="poly">
    <area target="" alt="dor_head" title="dor_head" href="" coords="276,17,310,17,318,33,270,34" shape="poly">
    <area target="" alt="dor_snout" title="dor_snout" href="" coords="282,19,311,6" shape="rect">
    <area target="" alt="dor_L_shoulder" title="dor_L_shoulder" href="" coords="270,34,292,31,292,56,263,56" shape="poly">
    <area target="" alt="dor_R_shoulder" title="dor_R_shoulder" href="" coords="292,54,323,56,316,34,292,30" shape="poly">
    <area target="" alt="dor_back" title="dor_back" href="" coords="264,55,324,52,326,95,266,96" shape="poly">
    <area target="" alt="dor_pelvis" title="dor_pelvis" href="" coords="266,97,325,97,310,123,286,124,274,113" shape="poly">
    <area target="" alt="vent_pelvis_genitals" title="vent_pelvis_genitals" href="" coords="267,290,322,289,313,304,295,318,274,306" shape="poly">
    <area target="" alt="vent_abdomen" title="vent_abdomen" href="" coords="264,250,323,249,326,270,323,289,263,289,263,270" shape="poly">
    <area target="" alt="vent_chest" title="vent_chest" href="" coords="270,222,314,222,319,233,323,248,262,249,266,231" shape="poly">
    <area target="" alt="vent_mouth_snout" title="vent_mouth_snout" href="" coords="295,205,11" shape="circle">
    <area target="" alt="vent_head" title="vent_head" href="" coords="271,223,283,201,295,195,310,208,314,221" shape="poly">
</map>
<!-- end image map -->
<BR>form here for adding injuries
'
	;
?>

<!-- INJURY SECTION -->
                      <br /> 


 <!--- injuries section ---->

<div class="table-responsive">
                    <table class="table table-bordered angelo_table" id="admittable" width="100%" cellspacing="0">
                        <thead>
                            <tr>
                                <th>Injury Site</th>
                                <th>Type of Injury</th>
								<th>Notes</th>
                                <th></th>
                            </tr>
                        </thead>
                  
                        <tbody>

                    <?php
                    //Get injury record
                    $stmt = $conn->prepare("SELECT * FROM rescue_injury_record WHERE patient_id=:patient_id");
                    $stmt->bindParam(':patient_id', $patient_id, PDO::PARAM_INT);

                    // initialise an array for the results
                    $injuries = array();
                    $stmt->execute();
							 	 
                    while ($row = $stmt->fetch(PDO::FETCH_ASSOC)) {

                        $injury_site = $row["injury_site"];
                        $injury_type = $row["injury_type"];
                        $injury_notes = $row["injury_notes"];

                        print '     
                            <tr><TD>' . $injury_site . '  </td><td> ' . $injury_type . ' </td><td> ' . $injury_notes . ' </td></tr>		
							'
;				
							;

                    }

                    ?>
						</tbody></table>

